// Mocks generated by Mockito 5.4.6 from annotations
// in playaround/test/dashboard/dashboard_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:playaround/models/dashboard_models.dart' as _i2;
import 'package:playaround/services/dashboard_service.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDashboardStats_0 extends _i1.SmartFake
    implements _i2.DashboardStats {
  _FakeDashboardStats_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [DashboardService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDashboardService extends _i1.Mock implements _i3.DashboardService {
  MockDashboardService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.DashboardStats> getUserStats() => (super.noSuchMethod(
        Invocation.method(
          #getUserStats,
          [],
        ),
        returnValue: _i4.Future<_i2.DashboardStats>.value(_FakeDashboardStats_0(
          this,
          Invocation.method(
            #getUserStats,
            [],
          ),
        )),
      ) as _i4.Future<_i2.DashboardStats>);

  @override
  _i4.Future<List<_i2.DashboardEvent>> getNearbyEvents({
    String? location,
    int? limit = 10,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getNearbyEvents,
          [],
          {
            #location: location,
            #limit: limit,
          },
        ),
        returnValue:
            _i4.Future<List<_i2.DashboardEvent>>.value(<_i2.DashboardEvent>[]),
      ) as _i4.Future<List<_i2.DashboardEvent>>);

  @override
  _i4.Future<List<_i2.FeaturedCoach>> getFeaturedCoaches({
    List<String>? sportsOfInterest,
    String? location,
    int? limit = 5,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFeaturedCoaches,
          [],
          {
            #sportsOfInterest: sportsOfInterest,
            #location: location,
            #limit: limit,
          },
        ),
        returnValue:
            _i4.Future<List<_i2.FeaturedCoach>>.value(<_i2.FeaturedCoach>[]),
      ) as _i4.Future<List<_i2.FeaturedCoach>>);

  @override
  _i4.Future<List<_i2.MatchmakingSuggestion>> getMatchmakingSuggestions(
          {int? limit = 10}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMatchmakingSuggestions,
          [],
          {#limit: limit},
        ),
        returnValue: _i4.Future<List<_i2.MatchmakingSuggestion>>.value(
            <_i2.MatchmakingSuggestion>[]),
      ) as _i4.Future<List<_i2.MatchmakingSuggestion>>);

  @override
  _i4.Future<List<_i2.ShopProduct>> getRecommendedProducts({
    List<String>? sportsOfInterest,
    int? limit = 4,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecommendedProducts,
          [],
          {
            #sportsOfInterest: sportsOfInterest,
            #limit: limit,
          },
        ),
        returnValue:
            _i4.Future<List<_i2.ShopProduct>>.value(<_i2.ShopProduct>[]),
      ) as _i4.Future<List<_i2.ShopProduct>>);

  @override
  _i4.Future<void> updateUserStats({
    int? sessionsIncrement,
    int? hoursIncrement,
    int? skillPointsIncrement,
    int? matchesIncrement,
    int? teamsIncrement,
    int? tournamentsIncrement,
    int? bookingsIncrement,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserStats,
          [],
          {
            #sessionsIncrement: sessionsIncrement,
            #hoursIncrement: hoursIncrement,
            #skillPointsIncrement: skillPointsIncrement,
            #matchesIncrement: matchesIncrement,
            #teamsIncrement: teamsIncrement,
            #tournamentsIncrement: tournamentsIncrement,
            #bookingsIncrement: bookingsIncrement,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
